<script setup>
import { computed, onMounted, ref, watch } from "vue";
import { storeToRefs } from "pinia";
import { useSession } from "../../stores/session.js";
import { listRoiSnapshots, listPromoPlans } from "../../api/marketing.js";
import { formatMoney } from "../../composables/money.js";
import { formatDateTime } from "../../composables/date.js";
import { t } from "../../composables/i18n.js";
import EmptyState from "../../components/EmptyState.vue";
import Select from "../../components/Select.vue";

const session = useSession();
const { activeCompany, user } = storeToRefs(session);

const loading = ref(false);
const error = ref("");
const rows = ref([]);
const plans = ref([]);
const planFilter = ref("");

const currency = computed(
	() => session.currentCompany?.default_currency || "UZS"
);
const lang = computed(() => user.value?.language || "en");

const planOptions = computed(() => [
	{ name: "", campaign_name: t("All promo plans") },
	...plans.value,
]);

async function loadPlans() {
	if (!activeCompany.value) {
		plans.value = [];
		return;
	}
	try {
		plans.value = await listPromoPlans({
			filters: { company: activeCompany.value },
			limit: 500,
		});
	} catch {
		plans.value = [];
	}
}

async function load() {
	loading.value = true;
	error.value = "";
	try {
		rows.value = await listRoiSnapshots({
			promo_plan: planFilter.value || undefined,
			limit: 500,
		});
	} catch (e) {
		error.value = e?.message || t("Something went wrong");
		rows.value = [];
	} finally {
		loading.value = false;
	}
}

onMounted(async () => {
	await loadPlans();
	await load();
});

watch(activeCompany, async () => {
	await loadPlans();
	await load();
});

watch(planFilter, load);

function roiClass(pct) {
	if (pct === null || pct === undefined || pct === "") return "text-secondary";
	const n = Number(pct);
	if (!Number.isFinite(n)) return "text-secondary";
	if (n >= 100) return "text-success fw-bold";
	if (n >= 50) return "text-warning fw-bold";
	return "text-danger fw-bold";
}

function fmtPct(pct) {
	if (pct === null || pct === undefined || pct === "") return "—";
	const n = Number(pct);
	if (!Number.isFinite(n)) return "—";
	return `${n.toFixed(2)}%`;
}

function planLabel(name) {
	const p = plans.value.find((x) => x.name === name);
	return p ? `${p.campaign_name}` : name;
}
</script>

<template>
	<div class="card">
		<div class="card-header d-flex flex-wrap gap-2 align-items-center">
			<h3 class="card-title mb-0">{{ t("Campaign ROI") }}</h3>
			<div class="ms-auto" style="min-width: 280px">
				<Select
					v-model="planFilter"
					:options="planOptions"
					value-key="name"
					size="sm"
				>
					<template #option="{ option }">
						{{ option.campaign_name }}<template v-if="option.name"> ({{ option.name }})</template>
					</template>
					<template #selected="{ option }">
						{{ option.campaign_name }}<template v-if="option.name"> ({{ option.name }})</template>
					</template>
				</Select>
			</div>
		</div>

		<div v-if="loading" class="card-body text-secondary">{{ t("Loading…") }}</div>
		<div v-else-if="error" class="card-body text-danger">{{ error }}</div>
		<EmptyState
			v-else-if="!rows.length"
			icon="ti-chart-line"
			:title="t('No ROI snapshots yet')"
			:description="t('Snapshots are generated by the daily ROI task for Active promo plans.')"
		/>
		<div v-else class="table-responsive">
			<table class="table table-vcenter card-table">
				<thead>
					<tr>
						<th>{{ t("Promo Plan") }}</th>
						<th>{{ t("Date") }}</th>
						<th class="text-end">{{ t("Units Sold") }}</th>
						<th class="text-end">{{ t("Incremental Units") }}</th>
						<th class="text-end">{{ t("Uplift Value") }}</th>
						<th class="text-end">{{ t("Gross ROI %") }}</th>
						<th class="text-end">{{ t("Net ROI %") }}</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="r in rows" :key="r.name">
						<td>
							<div>{{ planLabel(r.promo_plan) }}</div>
							<div class="small text-secondary font-monospace">{{ r.promo_plan }}</div>
						</td>
						<td>{{ formatDateTime(r.snapshot_date) }}</td>
						<td class="text-end font-monospace">{{ r.units_sold ?? 0 }}</td>
						<td class="text-end font-monospace">{{ r.incremental_units ?? 0 }}</td>
						<td class="text-end font-monospace">{{ formatMoney(r.uplift_value, currency, lang) }}</td>
						<td class="text-end font-monospace" :class="roiClass(r.gross_roi_pct)">
							{{ fmtPct(r.gross_roi_pct) }}
						</td>
						<td class="text-end font-monospace" :class="roiClass(r.net_roi_pct)">
							{{ fmtPct(r.net_roi_pct) }}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</template>
